export const LOADING = "LOADING";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGIN_USER";

export const CHAT_FETCHED = "CHAT_FETCHED";
export const MESSAGE_SENT = "MESSAGE_SENT";
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const PUSH_UNREAD_MESSAGE = "PUSH_UNREAD_MESSAGE";

export const UPDATE_UNREAD_MEASSAGES = "UPDATE_UNREAD_MEASSAGES";
export const CLEAR_UNREAD_MEASSAGES = "CLEAR_UNREAD_MEASSAGES";
